### PR TITLE
Use driver sent upstream

### PR DESCRIPTION
**Pull request by AdityaGarg8**
I have added the backlight support as well

### CODE REVIEW

**Comment by AdityaGarg8** [comment]
I better close it since the driver is good rn anyways.

**Comment by Redecorating** [comment]
i feel like you should be sending a pr to t2linux/apple-ib-drv instead of adding it onto this one. The keyboard backlight stuff hasn't been merged for a while and needs some improvement, so if you want the updated version of apple-ib-tb merged, i would expect it would be more likely to get merged separate from the kbd bl stuff than together

**Comment by AdityaGarg8** [comment]
I didn't find much difference in the updated version.

**Comment by AdityaGarg8** [comment]
The driver probably shall have to wait to get upstreamed I guess.

**Pull request closed without merging**
